site_name: Tesouro Direto

theme:
  name: "material"
  palette:
    primary: "teal"

nav:
  - Visão geral: index.md
  - Apresentações:
      - Apresentação 1: apresentacao1.md
  - Planejamento:
      - Cronograma: cronograma.md
      - Heatmap: heatmap.md
      - Metodologia: metodologia.md
      - Ferramentas: ferramentas.md
  - Pré-rastreabilidade:
      - RichPicture: richPicture.md
  - Elicitação:
      - Personas: personas.md
      - Introspecção: introspeccao.md

